name: Generate and Push Code

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Clean up generated files (exclude .placeholder)
        run: |
          find fluent-bot-api-library/src/main/java/it/marcodemartino/fluentbotapi -type f ! -name ".placeholder" -exec rm -f {} +

      - name: Run Maven install
        id: build
        run: mvn install --no-transfer-progress

      - name: Set commit message
        id: commit_message_step
        run: |
          echo 'commit_message<<EOF' >> $GITHUB_OUTPUT
          echo "Generated code" >> $GITHUB_OUTPUT
          echo >> $GITHUB_OUTPUT
          echo >> $GITHUB_OUTPUT
          echo "skip-checks: true" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      
      # Quick and dirty step to get rid of the temporary file holding the commit message
      - run: rm -rf commitmessage.txt

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "${{ steps.commit_message_step.outputs.commit_message }}"
