name: Generate and Push Code

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Clean up generated files (exclude .placeholder)
        run: |
          find fluent-bot-api-library/src/main/java/it/marcodemartino -type f ! -name ".placeholder" -exec rm -f {} +

      - name: Pull latest changes
        run: git pull --rebase origin ${{ github.head_ref }}

      - name: Run Maven install
        id: build
        run: mvn install --no-transfer-progress

      - name: Check if there are changes
        id: check_changes
        run: |
          git diff --exit-code || echo "Generated files have changed."

      - name: Commit and push generated code
        if: steps.check_changes.outcome == 'success'  # Only commit if changes are detected
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-update generated code"
          git push origin HEAD:${{ github.head_ref }}
