name: Generate and Push Code

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Maven install
        id: build
        run: mvn install

      - name: List files to verify generation
        run: ls -R fluent-bot-api-library/src/main/java/it/marcodemartino

      - name: Stage generated files
        run: git add fluent-bot-api-library/src/main/java/it/marcodemartino/*.java --force

      - name: Check for generated changes
        id: check_changes
        run: git diff --exit-code || echo "Generated files have changed."

      - name: Check git status
        run: git status

      - name: Commit and push generated code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-update generated code"
          git push
